apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stock-portfolio
  name: stock-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-portfolio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stock-portfolio
    spec:
      containers:
      - image: stock-portfolio
        name: stock-portfolio
        imagePullPolicy: Never
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stock-portfolio
  name: stock-portfolio
spec:
  ports:
  - name: 9999-9999
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: stock-portfolio
  type: ClusterIP
status:
  loadBalancer: {}
